[package]
name = "kemuri-probes"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kemuri-core = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
socket2 = { workspace = true }
hickory-resolver = { workspace = true }
rustls = { workspace = true }
tokio-rustls = { workspace = true }
webpki-roots = { workspace = true }

[lints]
workspace = true
