[package]
name = "kemuri-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
criterion = { workspace = true }
serde_yaml = { workspace = true }

[[bench]]
name = "core"
harness = false
